apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-classifier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-classifier
  template:
    metadata:
      labels:
        app: ml-classifier
    spec:
      containers:
        - name: ml-classifier
          image: ai-doc-detection-hub-ml-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: ml-classifier
spec:
  type: ClusterIP
  selector:
    app: ml-classifier
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
